### ISSUE TITLE
newly opened window in VS code is marked as dirty

### ISSUE THREAD

**Issue by nagendramishr** [bajcmartinez/jwt-vscode#1]
If you're looking to decode a JWT, you want to be able to see it and then forget about it.  I think the extension should not mark the window as dirty.   Clearing that would reduce at least 1 click when you close the window.  Otherwise, I think it's great.

**Comment by jcmartinezdev** [comment]
You have a really good point here. I was doing some testing and I find a way to fix that, I'll push the changes soon enough. Thanks for reporting!
